[package]
name = "wackypixels"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
flate2 = "1.1.9"
hound = "3.5.1"
image = "0.25.9"
lopdf = "0.39.0"
rand = "0.10.0"
xz2 = "0.1.7"
